module.exports = {
  appName: 'cmt-api',
  console_url: 'http://localhost:4206',
  port: 1400,
  baseUrl: 'http://localhost:4206',

  debug: {
    request: ['error', 'info'],
    log: ['info', 'error', 'warning']
  },

  constants: {
    s3Prefix: 'local',
    private_bucket : 'tspl-cmt-data',
    public_bucket : 'tspl-cmt-publicassets-data',
    API_BASEPATH: 'localhost:1400',
    DEFAULT_COUNTRY: 'IND',
    DEFAULT_TIMEZONE: 'Asia/Kolkata',
    SERVER_TIMEZONE: 'Asia/Kolkata',
    EXPIRATION_PERIOD: '730h',
    WELCOME_MSG: `this chatbot welcomes you powered by ai, here we will solve your quries realted to home properties and realestate stuff, we will give answer only related to these keywords only, here is the keywords:
    Homeownership costs,
    Down payment,
    Mortgage payments,
    Interest rates,
    Property taxes,
    Closing costs,
    Appraisal fees,
    Inspection fees,
    Title insurance,
    Private mortgage insurance,
    Homeowners insurance,
    PMI,
    HOA,
    Home warranty,
    Homeowner association fees,
    Property value,
    Home improvements,
    Renovation costs,
    Energy-efficient features,
    Maintenance costs,
    Moving expenses,
    Property tax rates,
    Loan programs,
    Refinancing,
    Loan pre-approval,
    Debt-to-income ratio,
    Credit score,
    Adjustable-rate mortgages,
    Fixed-rate mortgages,
    Mortgage amortization,
    Principal payments,
    Closing disclosures,
    Loan estimates,
    Origination fees,
    Discount points,
    Broker fees,
    Lender fees,
    Closing agents,
    Property surveys,
    Escrow accounts,
    Good faith estimates,
    Underwriting requirements,
    Title searches,
    Title insurance premiums,
    Home appraisals,
    Home inspections,
    Home warranties,
    Contract contingencies,
    Homeowner's association dues,
    Appraisal contingency,
    Inspection contingency,
    Financing contingency,
    Occupancy contingency,
    Closing contingency,
    Property tax prorations,
    Homeowner's insurance premiums,
    Tax deductions,
    Tax credits,
    Energy-efficient tax credits,
    First-time homebuyer tax credits,
    Mortgage interest deduction,
    Home equity loans,
    Home equity lines of credit,
    Cash-out refinancing,
    Reverse mortgages,
    Closing attorneys,
    Closing fees,
    Title searches,
    Title transfer fees,
    Recording fees,
    Property surveys,
    Zoning regulations,
    Building codes,
    Homeowner's association bylaws,
    Disclosure requirements,
    Real estate agents' fees,
    MLS,
    Multiple listing services fees,
    Buyer's agents,
    Seller's agents,
    Buyer's agent commission,
    Seller's agent commission,
    Dual agency,
    Exclusive agency,
    Exclusive right-to-sell,
    Open listing,
    Net listing,
    Buyer's market,
    Seller's market,
    Real estate brokerages,
    Real estate franchising,
    Discount real estate brokers,
    Online real estate brokers,
    Virtual tours,
    Property photos,
    Home staging,
    Negotiation skills,
    Home affordability calculators,
    Home equity calculators,
    Rent vs buy calculators,
    Mortgage calculators,
    Debt consolidation loans,
    Neighborhood,
    Community,
    Proximity,
    Distance,
    Accessibility,
    Walkability,
    Commute,
    Transportation,
    Public transit,
    Highways,
    Traffic,
    Parking,
    Schools,
    School district,
    Education,
    Libraries,
    Parks,
    Recreation,
    Entertainment,
    Restaurants,
    Shopping,
    Grocery stores,
    Farmers markets,
    Hospitals,
    Medical facilities,
    Doctor's offices,
    Dentists,
    Optometrists,
    Veterinarians,
    Animal hospitals,
    Churches,
    Mosques,
    Temples,
    Synagogues,
    Civic organizations,
    Volunteer opportunities,
    Political affiliations,
    Crime rate,
    Safety,
    Police presence,
    Emergency response times,
    Disaster preparedness,
    Weather,
    Climate,
    Views,
    Sunlight,
    Noise level,
    Air quality,
    Water quality,
    Natural features,
    Trees,
    Parks and recreation areas,
    Beaches,
    Lakes,
    Rivers,
    Mountains,
    Deserts,
    Coastal areas,
    Historical landmarks,
    Museums,
    Art galleries,
    Theaters,
    Live music venues,
    Nightlife,
    Cultural events,
    Festivals,
    Parades,
    Sporting events,
    Gyms,
    Yoga studios,
    Dance studios,
    Swimming pools,
    Golf courses,
    Tennis courts,
    Bike trails,
    Hiking trails,
    Camping areas,
    Ski resorts,
    Public spaces,
    Playgrounds,
    Dog parks,
    Green spaces,
    Farmland,
    Ranchland,
    Wineries,
    Breweries,
    Distilleries,
    Airports,
    Train stations,
    Bus stations,
    Shopping centers,
    Outlet malls,
    Antique shops,
    Artisanal shops,
    Farmers markets,
    Festive markets,
    Art and craft fairs,
    Pop-up shops,
    Food trucks,
    Local businesses,
    Square footage,
    Lot size,
    Bedrooms,
    Bathrooms,
    Living room,
    Dining room,
    Kitchen,
    Master bedroom,
    Walk-in closet,
    En suite bathroom,
    Bonus room,
    Office,
    Den,
    Family room,
    Great room,
    Loft,
    Sunroom,
    Basement,
    Attic,
    Garage,
    Carport,
    Driveway,
    Yard,
    Deck,
    Patio,
    Balcony,
    Porch,
    Pool,
    Jacuzzi,
    Sauna,
    Fireplace,
    Vaulted ceiling,
    High ceilings,
    Crown molding,
    Wainscoting,
    Built-in shelving,
    Custom cabinetry,
    Granite countertops,
    Stainless steel appliances,
    Gas range,
    Kitchen island,
    Breakfast bar,
    Pantry,
    Formal dining room,
    Eat-in kitchen,
    Open concept,
    Split floor plan,
    Ranch-style,
    Two-story,
    Multi-level,
    Traditional style,
    Contemporary style,
    Modern style,
    Mediterranean style,
    Colonial style,
    Craftsman style,
    Tudor style,
    Victorian style,
    Cape Cod style,
    A-frame style,
    Bungalow style,
    Cottage style,
    Ranch style,
    Split-level style,
    Gabled roof,
    Hip roof,
    Mansard roof,
    Gambrel roof,
    Cathedral ceiling,
    Skylights,
    Ceiling fans,
    Natural lighting,
    Recessed lighting,
    Chandelier,
    Pendant lights,
    Bay window,
    Garden window,
    Picture window,
    Sliding glass door,
    French doors,
    Pocket doors,
    Arched doorway,
    Staircase,
    Balustrade,
    Crown molding,
    Baseboards,
    Hardwood floors,
    Wall-to-wall carpeting,
    Tile flooring,
    Marble flooring,
    Stone flooring,
    Laminate flooring,
    Vinyl flooring,
    Wood paneling,
    Wallpaper,
    Accent walls,
    Neutral colors,
    Bold colors,
    Custom finishes,
    Upgrades,
    New construction,
    Pre-construction,
    Move-in ready,
    Fixer-upper,
    Renovated,
    Remodeled,
    Updated,
    Upgraded,
    Well-maintained,
    Turnkey,
    As-is,
    Needs work,
    Structural issues,
    Foundation,
    Roof,
    Windows,
    Doors,
    Plumbing,
    Electrical,
    Heating,
    Air conditioning,
    Ventilation,
    Insulation,
    Water damage,
    Mold,
    Mildew,
    Termites,
    Pest infestations,
    Radon,
    Asbestos,
    Lead-based paint,
    Hazardous materials,
    Building codes,
    Zoning laws,
    Permitting,
    Water supply,
    Sewer system,
    Septic system,
    Gas lines,
    Oil tank,
    Crawl space,
    Attic,
    Basement,
    Garage,
    Carport,
    Driveway,
    Sidewalks,
    Fencing,
    Landscaping,
    Trees,
    Shrubs,
    Lawn,
    Outdoor lighting,
    Decks,
    Patios,
    Porches,
    Balconies,
    Swimming pools,
    Hot tubs,
    Saunas,
    Fireplaces,
    Chimneys,
    Siding,
    Brickwork,
    Stucco,
    Stone,
    Wood,
    Vinyl,
    Aluminum,
    Copper,
    Steel,
    Appliances,
    Cabinets,
    Countertops,
    Flooring,
    Walls,
    Ceilings,
    Lighting,
    Fixtures,
    Plumbing fixtures,
    Hardware,
    Insulation,
    Ductwork,
    Soundproofing,
    Windows,
    Doors,
    Trim,
    Painting,
    Wallpaper,
    Molding,
    Baseboards,
    Closets,
    Shelving,
    Storage,
    Bathroom fixtures,
    Shower,
    Bathtub,
    Toilet,
    Sink,
    Vanity,
    School district,
    School ratings,
    Elementary school,
    Middle school,
    High school,
    Public school,
    Charter school,
    Private school,
    Magnet school,
    IB program,
    AP classes,
    Special education,
    Gifted and talented programs,
    Sports teams,
    Extracurricular activities,
    School demographics,
    Student-teacher ratio,
    Graduation rates,
    College acceptance rates,
    Advanced degree rates,
    Teacher quality,
    School safety,
    School funding,
    Property taxes,
    Millage rates,
    PTA,
    Parent involvement,
    Parent-teacher conferences,
    Back-to-school nights,
    School orientations,
    School choice,
    Redistricting,
    School calendars,
    School start times,
    Bus routes,
    Before- and after-school care,
    Extended school day,
    Summer school,
    Homeschooling,
    Tutoring,
    Test preparation,
    SAT,
    ACT,
    College entrance exams,
    Advanced placement exams,
    Vocational training,
    Apprenticeships,
    Work-study programs,
    Dual enrollment,
    Early admission,
    Admissions criteria,
    Enrollment deadlines,
    School tours,
    Open houses,
    Enrollment fairs,
    School uniforms,
    Dress codes,
    School supplies,
    School lunches,
    Healthy school initiatives,
    Parent-teacher organizations,
    Volunteer opportunities,
    Booster clubs,
    Student government,
    Social activities,
    Clubs and organizations,
    Community service opportunities,
    Service clubs,
    Student publications,
    Creative writing clubs,
    Drama clubs,
    Music programs,
    Band,
    Choir,
    Orchestra,
    Art classes,
    Dance classes,
    Theater classes,
    Gymnastics classes,
    Sports teams,
    Football,
    Basketball,
    Baseball,
    Softball,
    Volleyball,
    Soccer,
    Tennis,
    Golf,
    Cross country,
    Track and field,
    Swimming,
    Cheerleading,
    Pep rallies,
    Homecoming,
    Prom,
    Senior activities,
    Yearbook,
    Class rings,
    Graduation,
    Alumni networks,
    Public transportation,
    Bus routes,
    Bus stops,
    Bus schedules,
    Bus fares,
    Bus passes,
    Light rail,
    Subway,
    Train station,
    Train schedules,
    Train fares,
    Train passes,
    Commuter rail,
    Commuter trains,
    Commuter schedules,
    Commuter fares,
    Commuter passes,
    Express buses,
    Express trains,
    Park and ride,
    Transit-oriented development,
    Transit centers,
    Transit corridors,
    Transit lines,
    Transit options,
    Transit passes,
    Transit schedules,
    Transit fares,
    Transit hubs,
    Transit maps,
    Bike-sharing,
    Scooter-sharing,
    Car-sharing,
    Ride-sharing,
    Vanpool,
    Carpools,
    Guaranteed ride home,
    HOV lanes,
    Bike lanes,
    Bike paths,
    Bike racks,
    Pedestrian paths,
    Sidewalks,
    Street crossings,
    Accessibility,
    ADA-compliant,
    Wheelchair-accessible,
    Handicap-accessible,
    Elevators,
    Escalators,
    Stairs,
    Ramps,
    Braille signage,
    Audio announcements,
    Digital signage,
    Real-time information,
    GPS tracking,
    Ticket vending machines,
    Ticket booths,
    Fare collection,
    Cashless payments,
    Contactless payments,
    Smart cards,
    Mobile apps,
    Payment kiosks,
    Park-and-ride lots,
    Transit shelters,
    Transit benches,
    Security cameras,
    Security patrols,
    Lighting,
    Trash cans,
    Recycling bins,
    Restrooms,
    Water fountains,
    Wi-Fi,
    Charging stations,
    Green features,
    Renewable energy,
    Electric buses,
    Hybrid buses,
    Low-emission buses,
    Low-emission trains,
    Energy-efficient trains,
    Bike storage,
    Bike repair,
    Bike rentals,
    Bike lockers,
    Bike racks,
    Bike paths,
    Bike lanes,
    Shuttle service,
    Taxis,
    Limousines,
    Ride-hailing services,
    Uber,
    Lyft,
    Car rental,
    Car lease,
    Car purchase,
    Nightlife,
    Bars,
    Nightclubs,
    Lounges,
    Pubs,
    Breweries,
    Wineries,
    Rooftop bars,
    Dive bars,
    Sports bars,
    Karaoke bars,
    Dance clubs,
    Live music,
    Jazz clubs,
    Blues clubs,
    Rock clubs,
    Hip-hop clubs,
    DJ events,
    Open mic nights,
    Comedy clubs,
    Dinner theaters,
    Performance venues,
    Symphony orchestras,
    Ballet,
    Theater companies,
    Opera,
    Art galleries,
    Museums,
    Exhibitions,
    Festivals,
    Food festivals,
    Wine festivals,
    Beer festivals,
    Music festivals,
    Film festivals,
    Cultural events,
    Holiday events,
    Parades,
    Fireworks,
    Farmer's markets,
    Craft fairs,
    Art fairs,
    Street festivals,
    Carnivals,
    Amusement parks,
    Water parks,
    Zoos,
    Aquariums,
    Golf courses,
    Driving ranges,
    Miniature golf,
    Tennis courts,
    Volleyball courts,
    Beaches,
    Waterfronts,
    Lakes,
    Rivers,
    Hiking trails,
    Biking trails,
    Canoeing,
    Kayaking,
    Fishing,
    Hunting,
    Archery,
    Gun ranges,
    Cross-country skiing,
    Ice skating,
    Snowboarding,
    Skiing,
    Tubing,
    Snowshoeing,
    Outdoor adventure,
    Guided tours,
    Walking tours,
    Haunted tours,
    Ghost tours,
    Winery tours,
    Brewery tours,
    Historical landmarks,
    National parks,
    State parks,
    Botanical gardens,
    Nature reserves,
    Wildlife preserves,
    Scenic routes,
    Drives,
    Road trips,
    Day trips,
    Weekend getaways,
    Spa retreats,
    Wellness retreats,
    Yoga classes,
    Pilates classes,
    Martial arts classes,
    Gymnastics classes,
    Dance classes,
    Cooking classes,
    Art classes,
    Writing classes,
    Language classes,
    Outdoor space,
    Backyard,
    Front yard,
    Lawn,
    Garden,
    Patio,
    Porch,
    Deck,
    Terrace,
    Balcony,
    Veranda,
    Outdoor kitchen,
    Grill,
    Fire pit,
    Pool,
    Hot tub,
    Jacuzzi,
    Water feature,
    Fountain,
    Pond,
    Stream,
    River,
    Lake,
    Ocean,
    Mountain view,
    City view,
    Country view,
    Park,
    Playground,
    Dog park,
    Skate park,
    Walking trails,
    Biking trails,
    Hiking trails,
    Running trails,
    Cross-country skiing trails,
    Snowmobiling trails,
    Snowshoeing trails,
    Beach,
    Picnic area,
    Campfire area,
    Hammock,
    Swing,
    Tree house,
    Shed,
    Garden shed,
    Greenhouse,
    Arbors,
    Pergola,
    Sunshade,
    Gazebo,
    Fencing,
    Brickwork,
    Stone work,
    Flower beds,
    Raised beds,
    Vegetable garden,
    Fruit trees,
    Landscape lighting,
    Garden art,
    Water conservation,
    Drought-resistant plants,
    Native plants,
    Xeriscaping,
    Garden design,
    Irrigation,
    Rainwater harvesting,
    Drip irrigation,
    Sprinklers,
    Outdoor lighting,
    Security lighting,
    Motion sensor lighting,
    Solar lighting,
    Landscape design,
    Water features design,
    Deck design,
    Patio design,
    Hardscaping design,
    Softscaping design,
    Garden architecture,
    Garden pathways,
    Retaining walls,
    Stone walkways,
    Steps,
    Benches,
    Picnic tables,
    Planters,
    Topiaries,
    Landscaping service,
    Garden maintenance,
    Tree trimming,
    Lawn care,
    Seasonal maintenance,
    Insect control,
    Pest control,
    Weed control,
    Lawn fertilization,
    Pruning,
    Leaf removal,
    Snow removal.
    so how may i help you with?
    `,
    JWT_SECRET: 'jwtsecret',
    TIMEZONE_API_URL :'https://worldtimeapi.org/api/timezone',
    S3_NEW_BASE: 'https://tspl-cmt-publicassets.s3.ap-south-1.amazonaws.com',
    S3_BASE_URL: 'https://ethicalcode-assets.s3-us-west-2.amazonaws.com',
    MAIL_FROM: 'demo1.webfirminfotech@gmail.com', // mailgun=>demo1.webfirminfotech@gmail.com, aws=>no-reply@intelllivisit.com
    FCM_SERVER_KEY: "AAAABKcvtL0:APA91bE4wKQ-WgfBvDZIB-u_hNVYLp_ZyN3-gihekHX4BrHUsog21DnBfPiFjJeQ7MfgoE70qSU3DDyQM6dcQoyzKHXe_D23M8Mn6P1U8zF_7Dd72cX0seW17IA7FVjQGdd5HwRjkkV7",
    status: {
      new: 'NEW',
      pending: 'PENDING',
      assigned: 'ASSIGNED',
      inqueue: 'INQUEUE',
      inprocess: 'INPROCESS',
      inreview: 'INREVIEW',
      done: 'DONE',
      completed: 'COMPLETED',
      tbd: 'TBD'
    }
  },

  connections: {
    db: process.env.DB
  }
}
